### ISSUE TITLE
Style family 'section' exists in RNG but is missing in spec

### ISSUE THREAD

**Issue by svanteschubert** [oasis-tcs/odf-tc#49]
## Problem
For the attribute style:family there is a value 'section' in our RelaxNG grammar, see ODF 1.3: 
https://docs.oasis-open.org/office/OpenDocument/v1.3/os/schemas/OpenDocument-v1.3-schema-rng.html#12668 
but in the style:family listing of ODF 1.3 there is no such @style:family 
https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#attribute-style_family

## Proposal
Just add the missing 'section' value to the attribute style:family listing of 
https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part3-schema/OpenDocument-v1.3-os-part3-schema.html#attribute-style_family

**Comment by franciscave** [comment]
Correction made in Github working draft of Part 3, but not yet listed in the Appendix. We need to add a new Appendix for purely editorial changes, as agreed on the last TC call.

I note that the text generated from the schema for the attribute @style:family does not include the enumerated list of possible values of this attribute. The reason for this is that the XSLT script that generates text from the schema currently only extracts values (rng:value) when they are the immediate child of a choice (rng:choice), but in the case of @style:family the values are not immediate children of the choice (rng:choice/rng:group/rng:attribute/rng:value). This might be fixed in the XSLT, which would make this kind of error easier to spot.

**Comment by franciscave** [comment]
The ODF TC decided a while ago (minute reference?) not to add an Appendix for purely editorial changes, but instead to refer implementers to issues in GitHub.

**Comment by franciscave** [comment]
Closing this issue, as it has been resolved by an editorial correction in Part 3.
